apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: /tmp
    server: 10.95.55.205
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/lilong/datastore"
