apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-etcd
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/disk01/vol3"
